services:
  tier-fever:
    build: .
    container_name: tier-fever
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./flask_session:/tier-fever/flask_session
      - ./categories:/tier-fever/categories
      - ./static:/tier-fever/static
      - ./templates:/tier-fever/templates
      - ./docs:/tier-fever/docs
    networks:
      - pertuz-net

networks:
  pertuz-net:
    external: true
